### ISSUE TITLE
Class goals

### ISSUE THREAD

**Issue by hubyeti** [peakchuckle/github-for-developers-7#1]
Please tell us one thing you would like to learn in today's class!

**Comment by peakchuckle** [comment]
how to clone


On 4 November 2015 at 10:01, Certify Yeti <notifications@github.com> wrote:

> Please tell us one thing you would like to learn in today's class!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/peakchuckle/github-for-developers-7/issues/1>.
>



-- 
pgp <http://pgp.mit.edu/pks/lookup?op=get&search=0x8EAE6802CE30F0BC>|xmpp
<http://is.gd/5aTbaf>|skype <http://is.gd/BdJTAz>
